/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.semi1.pos;

import com.semi1.data.MemberDAO;
import com.semi1.data.MemberDTO;
import com.semi1.data.OddtDAO;
import com.semi1.data.OddtDTO;
import com.semi1.data.ProductDAO;
import com.semi1.data.ProductDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class PayCash extends javax.swing.JFrame implements ActionListener{
    private MainHome mh;
    private HashMap<Integer,String[]> map;
    private MemberDTO memberDto;
    private OddtDAO oddtDao = new OddtDAO();
    private ProductDAO productDao = new ProductDAO();
    private MemberDAO memberDao = new MemberDAO();
    /**
     * Creates new form PayCash
     */
    public PayCash() {
        initComponents();
    }
    public PayCash(MainHome mh) {
        this();
        this.mh = mh;
        init();
    }
    private void init(){
        tfCuTel.setText(mh.getCuTel());
        tfPrice.setText(mh.getTmoney());
        addEvent();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        map = mh.getMap();
        memberDto = mh.getMemberDto();
    }
    private void addEvent(){
        bt60.addActionListener(this);
        bt61.addActionListener(this);
        bt62.addActionListener(this);
        bt63.addActionListener(this);
        bt64.addActionListener(this);
        bt65.addActionListener(this);
        bt66.addActionListener(this);
        bt67.addActionListener(this);
        bt68.addActionListener(this);
        bt69.addActionListener(this);
        btBs6.addActionListener(this);
        btC6.addActionListener(this);
        btCom.addActionListener(this);
        btTel.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payPl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfCuTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        tfTakeM = new javax.swing.JTextField();
        btTel = new javax.swing.JButton();
        tfBackM = new javax.swing.JTextField();
        calcPl6 = new javax.swing.JPanel();
        bt60 = new javax.swing.JButton();
        bt61 = new javax.swing.JButton();
        bt62 = new javax.swing.JButton();
        bt63 = new javax.swing.JButton();
        bt64 = new javax.swing.JButton();
        bt65 = new javax.swing.JButton();
        bt66 = new javax.swing.JButton();
        bt67 = new javax.swing.JButton();
        bt68 = new javax.swing.JButton();
        btC6 = new javax.swing.JButton();
        btCom = new javax.swing.JButton();
        btBs6 = new javax.swing.JButton();
        bt69 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        payPl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payPl.setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 98, 112));
        jLabel2.setText("TEL");
        jLabel2.setFocusable(false);

        tfCuTel.setEditable(false);
        tfCuTel.setBackground(new java.awt.Color(255, 255, 255));
        tfCuTel.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        tfCuTel.setForeground(new java.awt.Color(57, 98, 112));
        tfCuTel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCuTel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfCuTel.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCuTel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCuTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("받을 금액");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("거스름돈");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("받은 금액");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setFocusable(false);

        tfPrice.setBackground(new java.awt.Color(242, 242, 242));
        tfPrice.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        tfPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPrice.setText("0");
        tfPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfPrice.setFocusable(false);

        tfTakeM.setBackground(new java.awt.Color(242, 242, 242));
        tfTakeM.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        tfTakeM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTakeM.setText("0");
        tfTakeM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfTakeM.setFocusable(false);

        btTel.setBackground(new java.awt.Color(255, 153, 0));
        btTel.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btTel.setForeground(new java.awt.Color(255, 255, 255));
        btTel.setText("현금영수증");
        btTel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btTel.setFocusable(false);

        tfBackM.setBackground(new java.awt.Color(242, 242, 242));
        tfBackM.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        tfBackM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfBackM.setText("0");
        tfBackM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfBackM.setFocusable(false);

        calcPl6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        calcPl6.setEnabled(false);
        calcPl6.setFocusable(false);

        bt60.setBackground(new java.awt.Color(51, 153, 255));
        bt60.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt60.setForeground(new java.awt.Color(255, 255, 255));
        bt60.setText("7");
        bt60.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt60.setFocusable(false);

        bt61.setBackground(new java.awt.Color(51, 153, 255));
        bt61.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt61.setForeground(new java.awt.Color(255, 255, 255));
        bt61.setText("8");
        bt61.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt61.setFocusable(false);

        bt62.setBackground(new java.awt.Color(51, 153, 255));
        bt62.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt62.setForeground(new java.awt.Color(255, 255, 255));
        bt62.setText("9");
        bt62.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt62.setFocusable(false);

        bt63.setBackground(new java.awt.Color(51, 153, 255));
        bt63.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt63.setForeground(new java.awt.Color(255, 255, 255));
        bt63.setText("4");
        bt63.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt63.setFocusable(false);

        bt64.setBackground(new java.awt.Color(51, 153, 255));
        bt64.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt64.setForeground(new java.awt.Color(255, 255, 255));
        bt64.setText("5");
        bt64.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt64.setFocusable(false);

        bt65.setBackground(new java.awt.Color(51, 153, 255));
        bt65.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt65.setForeground(new java.awt.Color(255, 255, 255));
        bt65.setText("6");
        bt65.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt65.setFocusable(false);

        bt66.setBackground(new java.awt.Color(51, 153, 255));
        bt66.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt66.setForeground(new java.awt.Color(255, 255, 255));
        bt66.setText("1");
        bt66.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt66.setFocusable(false);

        bt67.setBackground(new java.awt.Color(51, 153, 255));
        bt67.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt67.setForeground(new java.awt.Color(255, 255, 255));
        bt67.setText("2");
        bt67.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt67.setFocusable(false);

        bt68.setBackground(new java.awt.Color(51, 153, 255));
        bt68.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt68.setForeground(new java.awt.Color(255, 255, 255));
        bt68.setText("3");
        bt68.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt68.setFocusable(false);

        btC6.setBackground(new java.awt.Color(51, 153, 255));
        btC6.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btC6.setForeground(new java.awt.Color(255, 255, 255));
        btC6.setText("C");
        btC6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btC6.setFocusable(false);
        btC6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btC6ActionPerformed(evt);
            }
        });

        btCom.setBackground(new java.awt.Color(255, 153, 0));
        btCom.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btCom.setForeground(new java.awt.Color(255, 255, 255));
        btCom.setText("계산 완료");
        btCom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btCom.setFocusable(false);

        btBs6.setBackground(new java.awt.Color(51, 153, 255));
        btBs6.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        btBs6.setForeground(new java.awt.Color(255, 255, 255));
        btBs6.setText("←");
        btBs6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btBs6.setFocusable(false);

        bt69.setBackground(new java.awt.Color(51, 153, 255));
        bt69.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        bt69.setForeground(new java.awt.Color(255, 255, 255));
        bt69.setText("0");
        bt69.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt69.setFocusable(false);

        javax.swing.GroupLayout calcPl6Layout = new javax.swing.GroupLayout(calcPl6);
        calcPl6.setLayout(calcPl6Layout);
        calcPl6Layout.setHorizontalGroup(
            calcPl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPl6Layout.createSequentialGroup()
                .addGroup(calcPl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(calcPl6Layout.createSequentialGroup()
                        .addComponent(bt60, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt61, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt62, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calcPl6Layout.createSequentialGroup()
                        .addComponent(bt63, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt64, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt65, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calcPl6Layout.createSequentialGroup()
                        .addComponent(bt66, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt67, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt68, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calcPl6Layout.createSequentialGroup()
                        .addComponent(btC6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt69, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBs6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        calcPl6Layout.setVerticalGroup(
            calcPl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPl6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(calcPl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt60, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt61, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt62, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt63, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt64, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt65, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt66, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt67, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt68, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btC6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBs6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt69, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel1.setText("현금 계산");

        javax.swing.GroupLayout payPlLayout = new javax.swing.GroupLayout(payPl);
        payPl.setLayout(payPlLayout);
        payPlLayout.setHorizontalGroup(
            payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payPlLayout.createSequentialGroup()
                        .addGroup(payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrice)
                            .addComponent(tfTakeM)
                            .addComponent(tfBackM)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcPl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(payPlLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        payPlLayout.setVerticalGroup(
            payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calcPl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(payPlLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPrice)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTakeM)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(payPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfBackM)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payPl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payPl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btC6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt17;
    private javax.swing.JButton bt18;
    private javax.swing.JButton bt19;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt20;
    private javax.swing.JButton bt21;
    private javax.swing.JButton bt22;
    private javax.swing.JButton bt23;
    private javax.swing.JButton bt24;
    private javax.swing.JButton bt25;
    private javax.swing.JButton bt26;
    private javax.swing.JButton bt27;
    private javax.swing.JButton bt28;
    private javax.swing.JButton bt29;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt30;
    private javax.swing.JButton bt31;
    private javax.swing.JButton bt32;
    private javax.swing.JButton bt33;
    private javax.swing.JButton bt34;
    private javax.swing.JButton bt35;
    private javax.swing.JButton bt36;
    private javax.swing.JButton bt37;
    private javax.swing.JButton bt38;
    private javax.swing.JButton bt39;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt40;
    private javax.swing.JButton bt41;
    private javax.swing.JButton bt42;
    private javax.swing.JButton bt43;
    private javax.swing.JButton bt44;
    private javax.swing.JButton bt45;
    private javax.swing.JButton bt46;
    private javax.swing.JButton bt47;
    private javax.swing.JButton bt48;
    private javax.swing.JButton bt49;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt50;
    private javax.swing.JButton bt51;
    private javax.swing.JButton bt52;
    private javax.swing.JButton bt53;
    private javax.swing.JButton bt54;
    private javax.swing.JButton bt55;
    private javax.swing.JButton bt56;
    private javax.swing.JButton bt57;
    private javax.swing.JButton bt58;
    private javax.swing.JButton bt59;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt60;
    private javax.swing.JButton bt61;
    private javax.swing.JButton bt62;
    private javax.swing.JButton bt63;
    private javax.swing.JButton bt64;
    private javax.swing.JButton bt65;
    private javax.swing.JButton bt66;
    private javax.swing.JButton bt67;
    private javax.swing.JButton bt68;
    private javax.swing.JButton bt69;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btBs;
    private javax.swing.JButton btBs1;
    private javax.swing.JButton btBs2;
    private javax.swing.JButton btBs3;
    private javax.swing.JButton btBs4;
    private javax.swing.JButton btBs5;
    private javax.swing.JButton btBs6;
    private javax.swing.JButton btC;
    private javax.swing.JButton btC1;
    private javax.swing.JButton btC2;
    private javax.swing.JButton btC3;
    private javax.swing.JButton btC4;
    private javax.swing.JButton btC5;
    private javax.swing.JButton btC6;
    private javax.swing.JButton btCom;
    private javax.swing.JButton btOpen;
    private javax.swing.JButton btOpen1;
    private javax.swing.JButton btOpen2;
    private javax.swing.JButton btOpen3;
    private javax.swing.JButton btOpen4;
    private javax.swing.JButton btOpen5;
    private javax.swing.JButton btTel;
    private javax.swing.JPanel calcPl;
    private javax.swing.JPanel calcPl1;
    private javax.swing.JPanel calcPl2;
    private javax.swing.JPanel calcPl3;
    private javax.swing.JPanel calcPl4;
    private javax.swing.JPanel calcPl5;
    private javax.swing.JPanel calcPl6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel payPl;
    private javax.swing.JTextField tfBackM;
    private javax.swing.JTextField tfCuTel;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfTakeM;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        try{
            
        if(e.getSource()==bt60 || e.getSource()==bt61 || e.getSource()==bt62 ||
			e.getSource()==bt63 || e.getSource()==bt64 || e.getSource()==bt65 ||
			e.getSource()==bt66 || e.getSource()==bt67 || e.getSource()==bt68 ||
			e.getSource()==bt69) {

		if(tfTakeM.getText().equals("0")) {
			tfTakeM.setText("");
		}
				
		String str1 = tfTakeM.getText();
		JButton obj = (JButton)e.getSource();
		String str2 = obj.getText();
		tfTakeM.setText(str1+str2);
                int money1 = Integer.parseInt(tfPrice.getText());
                int money2 = Integer.parseInt(tfTakeM.getText());
                int bm = money2-money1;
                String sbm = Integer.toString(bm);
                tfBackM.setText(sbm);
	}
        if(e.getSource()==btC6) {
            tfTakeM.setText("0");
        }
        if(e.getSource()==btBs6) {
            String str = tfTakeM.getText();
            str= str.substring(0,str.length()-1);
            tfTakeM.setText(str);
            if(tfTakeM.getText().length()==0) {
                    tfTakeM.setText("0");
            }
        }
        if(e.getSource()==btTel){
            if(!tfCuTel.getText().isEmpty()){
                return;
            }
            String inputTel = JOptionPane.showInputDialog("전화번호를 입력하세요");
            String tel1 = inputTel.substring(0,3);
            String tel2 = inputTel.substring(3,inputTel.length()-4);
            String tel3 = inputTel.substring(inputTel.length()-4);
            String tel = tel1+"-"+tel2+"-"+tel3;
            tfCuTel.setText(tel);
        }
        if(e.getSource()==btCom){
            String bm = tfBackM.getText();
            int ibm = Integer.parseInt(bm);
            if(ibm<0){
                return;
            }
            String IO = "N";
            int type = JOptionPane.showConfirmDialog(this, "매장이용 여부","",JOptionPane.YES_NO_OPTION);
            if(type==JOptionPane.YES_OPTION){
                IO = "Y";
            }
            String sprice = tfPrice.getText();
            int iprice = Integer.parseInt(sprice);
            int od = oddtDao.insertOd(mh.getStno(), iprice);
            int odnum = oddtDao.lastOd();
            int oding = oddtDao.insertOdding(odnum);
            int to = oddtDao.insertTo(mh.getStno(), iprice, "Cash",odnum);
            
            OddtDTO dto = new OddtDTO();
            String[][] data = new String[map.size()][5];
            
            for(int i = 0; i<map.size(); i++) {
                String[] arr = map.get(i);
                if(arr[0].substring(arr[0].length()-2).equals("쿠폰")){
                    continue;
                }
                
                dto.setOddt_name(arr[0]);
                
                dto.setOddt_ice(arr[1]);
                dto.setOddt_shot(arr[2]);     
                String num = arr[3];
                int inum = Integer.parseInt(num);
                dto.setOddt_cnt(inum);
                dto.setSt_no(mh.getStno());
                dto.setOddt_io(IO);
                ProductDTO productDto = new ProductDTO();
                productDto = productDao.searchByName(arr[0]);
                int pdno = productDto.getPd_no();
                dto.setPd_no(pdno);
                dto.setOd_number(odnum);
                int cnt = oddtDao.insertOddt(dto);
                System.out.println(cnt);

            }
            int couponcnt = 0;
            int stampcnt = 0;
           
            for(int i = 0; i<map.size(); i++) {
                String[] arr = map.get(i);
                String price = arr[4];
                int pricecheck = Integer.parseInt(price);
                if(pricecheck>0){
                    stampcnt +=1;
                }else if(pricecheck<0){
                    stampcnt -=1;
                }
            }
            int curstamp = memberDto.getMem_stamp();
            if(memberDto.getMem_tel()!=null){
                curstamp += stampcnt;
                if(curstamp >=12){
                    curstamp -=12;
                    couponcnt +=1;
                }
                memberDto.setMem_stamp(curstamp);
                if(memberDto.getMem_id()==null){
                    int cnt = memberDao.tempStamp(memberDto);
                }else if(memberDto.getMem_id()!=null){
                    int cnt = memberDao.updateStamp(memberDto);
                }
            }
            if(memberDto.getMem_id()!=null){
                int curcoupon = memberDto.getMem_coupon();
                curcoupon += couponcnt;
                memberDto.setMem_coupon(curcoupon);
                int cnt = memberDao.updateCoupon(memberDto);
                System.out.println(cnt);
            }
            
            
            int cash = mh.getStartCash();
            cash += iprice;
            mh.setStartCash(cash);
            mh.showOding();
            mh.cleanUp();
            this.dispose();
        }
        }catch (SQLException ex) {
            Logger.getLogger(MainHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
